name: Dependabot Auto Test, Bump & Publish

permissions:
  contents: read # to be able to publish a GitHub release
#  issues: write # to be able to comment on released issues
#  pull-requests: write # to be able to comment on released pull requests
#  id-token: write # to enable use of OIDC for npm provenance

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - "*.x"
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm run vitest --coverage

  
  coveralls-runner:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run vitest --coverage --reporter=verbose
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov.info


  # doesn't actually work, yet.
  test-bump-and-publish-test:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - run: pnpm install --frozen-lockfile
      #- run: yarn --version
      #- run: cat /home/runner/work/_temp/.npmrc
      #- run: cat /home/runner/work/_temp/.yarnrc.yml
        #- run: yarn add -D husky
        #- run: yarn npm whoami --scope ${{secrets.scope}} --publish
        #- run: yarn npm publish --access public
        #- run: yarn npm publish --provenance --access public
      - run: pnpm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCOPE: ${{secrets.scope}}
          NODE_AUTH_TOKEN: ${{ secrets.VS_NPM_TOKEN}}
          NPM_TOKEN: ${{ secrets.VS_NPM_TOKEN}}
          #YARN_NPM_CONFIG_PROVENANCE:
